-- move to the root container
ALTER SESSION SET CONTAINER = CDB$ROOT;
 
-- create 
CREATE PLUGGABLE DATABASE migratetest ADMIN USER PDBADMIN IDENTIFIED BY goracle ROLE=(DBA) DEFAULT TABLESPACE migratetest DATAFILE SIZE 256M AUTOEXTEND ON NEXT 128M MAXSIZE UNLIMITED;
 
-- open that pluggable database   
ALTER PLUGGABLE DATABASE migratetest OPEN;
ALTER PLUGGABLE DATABASE migratetest SAVE STATE;
 
-- current container is the pluggable database
ALTER SESSION SET CONTAINER = migratetest;
 
-- save some problems for ourselves if logins don't work (like when running tests)
ALTER PROFILE DEFAULT LIMIT FAILED_LOGIN_ATTEMPTS UNLIMITED;
 
-- actually create the user
-- setting default tablespaces, unlocking the account,
-- and granting quota on the Development tablespace
 
-- ***** CHANGES REQUIRED PAST THIS POINT! *****
-- change "goracle" to your user name everywhere in this file
 
-- the phrase after "IDENTIFIED BY" is your password
CREATE USER goracle IDENTIFIED BY goracle
    DEFAULT TABLESPACE migratetest
    QUOTA UNLIMITED ON migratetest
    TEMPORARY TABLESPACE TEMP
    ACCOUNT UNLOCK
    CONTAINER = CURRENT;
 
-- allow connections
GRANT CREATE SESSION TO goracle;
 
-- allow create of interesting objects
GRANT CREATE TABLE TO goracle;
GRANT CREATE SEQUENCE TO goracle;
GRANT CREATE PROCEDURE TO goracle;
GRANT CREATE TRIGGER TO goracle;
GRANT CREATE VIEW TO goracle;
GRANT CREATE SYNONYM TO goracle;
GRANT ALTER SESSION TO goracle;
GRANT EXECUTE ON SYS.UTL_RAW TO goracle;
GRANT EXECUTE ON SYS.DBMS_CRYPTO TO goracle;
GRANT EXECUTE ON SYS.DBMS_LOCK TO goracle;
GRANT EXECUTE ON DBMS_FLASHBACK TO goracle;
  
-- Now do all the steps to setup the role-based-permission bits needed for migratetest 0.4+
-- This repeats what's here https://confluence.aka.lgl.grungy.us/display/migratetest/migratetest+Oracle+User+Setup+Required+Starting+with+version+0.4
-- Create the bootstrap, almost-all-powerful MIGRATEOWNER role
CREATE ROLE MIGRATEOWNER;
  
-- grant the rights that it needs
GRANT CREATE SESSION TO MIGRATEOWNER WITH ADMIN OPTION;
GRANT ALTER SESSION TO MIGRATEOWNER WITH ADMIN OPTION;
GRANT CREATE ANY TABLE, DROP ANY TABLE TO MIGRATEOWNER WITH ADMIN OPTION;
GRANT CREATE SEQUENCE TO MIGRATEOWNER WITH ADMIN OPTION;
GRANT DROP ANY SEQUENCE, SELECT ANY SEQUENCE, CREATE ANY SEQUENCE TO MIGRATEOWNER WITH ADMIN OPTION;
GRANT DROP PUBLIC SYNONYM TO MIGRATEOWNER WITH ADMIN OPTION;
GRANT CREATE PUBLIC SYNONYM TO MIGRATEOWNER WITH ADMIN OPTION;
GRANT CREATE ROLE TO MIGRATEOWNER WITH ADMIN OPTION;
GRANT GRANT ANY ROLE TO MIGRATEOWNER WITH ADMIN OPTION;
GRANT CREATE TRIGGER TO MIGRATEOWNER WITH ADMIN OPTION;
GRANT CREATE ANY TRIGGER, DROP ANY TRIGGER TO MIGRATEOWNER WITH ADMIN OPTION;
GRANT CREATE USER TO MIGRATEOWNER;
GRANT DROP USER TO MIGRATEOWNER;
GRANT CREATE ANY INDEX TO MIGRATEOWNER WITH ADMIN OPTION;
GRANT SELECT_CATALOG_ROLE TO MIGRATEOWNER WITH ADMIN OPTION;
  
-- And these are needed for 0.5
GRANT EXECUTE_CATALOG_ROLE TO MIGRATEOWNER;
GRANT CREATE MATERIALIZED VIEW TO MIGRATEOWNER;
GRANT CREATE TABLE TO MIGRATEOWNER;
GRANT ADMINISTER SQL MANAGEMENT OBJECT TO MIGRATEOWNER;
  
-- finally, grant that role to your initial user
GRANT MIGRATEOWNER TO goracle;